### PR TITLE
Auto Shuffleboard Chooser 

### LINKED ISSUE #96: AutoBuilder.buildAutoChooser() called twice at robotInit()
https://github.com/robototes/Crescendo2024/blob/5e5ed4b1c32ddec2502690af5c22a474aaf4ad89/src/main/java/frc/team2412/robot/Robot.java#L91

Seems at least like a perf issue, and perhaps a crash if the drivebase subsystem isn't enabled.

### PR DESCRIPTION
**Pull request by kirbt**
Shuffleboard Auto Path Filtering based off:
- Start Position
- Game Piece Count (excludes preloaded)
- Vision

also added/tweaked a couple of autos cause why not

### CODE REVIEW

File: src/main/java/frc/team2412/robot/Robot.java [hunk 1]
```diff
@@ -145,7 +147,11 @@ public void autonomousInit() {
 
 		// Checks if FMS is attatched and enables joystick warning if true
 		DriverStation.silenceJoystickConnectionWarning(!DriverStation.isFMSAttached());
-		autoChooser.getSelected().schedule();
+		// autoChooser.getSelected().schedule();
+		System.out.println(AutoLogic.getSelected() != null);
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/Robot.java]: Ideally, this log message would be cleanup or be more descriptive.

File: src/main/java/frc/team2412/robot/Robot.java [hunk 2]
```diff
@@ -51,7 +49,7 @@ public static Robot getInstance() {
 	public MatchDashboard dashboard;
 	public AutoLogic autoLogic;
 
-	public SendableChooser<Command> autoChooser;
+	// public SendableChooser<Command> autoChooser;
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/Robot.java]: Can this commented code be cleaned up?

File: src/main/java/frc/team2412/robot/Robot.java [hunk 3]
```diff
@@ -86,17 +84,21 @@ public void robotInit() {
 
 		subsystems = new Subsystems();
 		controls = new Controls(subsystems);
-		autoLogic = new AutoLogic();
 
-		autoChooser = AutoBuilder.buildAutoChooser();
-		SmartDashboard.putData("Auto Chooser", autoChooser);
-		SmartDashboard.putString("current bot", getTypeFromAddress().toString());
+		AutoLogic.registerCommands();
+		// autoChooser = AutoBuilder.buildAutoChooser();
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/Robot.java]: Can this commented code be cleaned up?

File: src/main/java/frc/team2412/robot/Robot.java [hunk 4]
```diff
@@ -86,17 +84,21 @@ public void robotInit() {
...
 		if (Subsystems.SubsystemConstants.DRIVEBASE_ENABLED) {
-			autoChooser = AutoBuilder.buildAutoChooser();
-		} else {
-			autoChooser = new SendableChooser<>();
+			AutoLogic.initShuffleBoard();
 		}
 
+		// SmartDashboard.putData("Auto Chooser", autoChooser);
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/Robot.java]: Can this commented code be cleaned up?

File: src/main/java/frc/team2412/robot/util/DynamicSendableChooser.java [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+	/**
+	 * Returns the selected option. If there is none selected, it will return the default. If there is
+	 * none selected and no default, then it will return {@code null}.
+	 *
+	 * @return the option selected
+	 */
+	public T getSelected() {
+		m_mutex.lock();
+		try {
+			if (m_selected != null) {
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/util/DynamicSendableChooser.java:102]: Is there a way for the selected to not exist (ie fallback to the default)?

File: src/main/java/frc/team2412/robot/util/DynamicSendableChooser.java [hunk 6]
```diff
@@ -0,0 +1,174 @@
...
+						} else {
+							choice = null;
+							listener = null;
+						}
+						m_previousVal = val;
+					} finally {
+						m_mutex.unlock();
+					}
+					if (listener != null) {
+						listener.accept(choice);
```
Comment (bobtseattle) [inline src/main/java/frc/team2412/robot/util/DynamicSendableChooser.java:170]: Is it a problem if choice is null?

**Review by bobtseattle — DISMISSED** [review]
Looking pretty good.
We will have to figure out a way to let drive team know which of the combinations is tested and ready for competition.

File: src/main/java/frc/team2412/robot/Robot.java (hunk 1 above)
Comment (kirbt) [reply src/main/java/frc/team2412/robot/Robot.java]: I've removed it because that was just originally used for debug purposes

**Review by TAKBS2412 — DISMISSED** [review]

**Review by TAKBS2412 — COMMENTED** [review]
I believe this breaks the auto field preview, at least when I tested it with Amp side subwoofer, vision, 2 game objects, and the steal auto.

File: src/main/java/frc/team2412/robot/util/MatchDashboard.java [hunk 7]
```diff
@@ -20,7 +20,6 @@ public MatchDashboard(Subsystems s) {
 		tab.add(new FMSWidget()).withPosition(0, 0).withSize(4, 1);
 		tab.add(field).withPosition(0, 1).withSize(4, 3);
 		Robot r = Robot.getInstance();
-		tab.add("Auto Chooser", r.autoChooser).withPosition(4, 0).withSize(2, 1);
-		AutonomousField.configureShuffleboardTab(tab, 6, 0, "Auto Chooser", r::addPeriodic);
+		AutonomousField.configureShuffleboardTab(tab, 6, 0, "Available Auto Variants", r::addPeriodic);
```
Comment (KangarooKoala) [inline src/main/java/frc/team2412/robot/util/MatchDashboard.java]: I accidentally hardcoded `configureShuffleboardTab` to use "Auto Chooser" as the name instead of the `autoChooserName` argument [when making the subscriber](https://github.com/robototes/Crescendo2024/blob/main/src/main/java/frc/team2412/robot/util/AutonomousField.java#L39), so that will need to be fixed.

**Comment by kirbt** [comment]
Updates: 
Fixed Field Widget
Added Est. Time Widget

**Review by TAKBS2412 — APPROVED** [review]
